---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cert-manager-issuers-secrets
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  suspend: false
  secretTemplates:
    - name: cloudflare-api-token
      stringData:
        api-token: ENC[AES256_GCM,data:aRUWriwzGi2F/M86jD0OUsgmDVZktnUTPh+vQ8i4cLx80tmX6wuaLA==,iv:jlwWhY/e/hh4fbadfJiJRAFTgg0BHSz91ud2Skb9JuY=,tag:Rwi+GKEK9IctUUcqqlEMig==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc3ZSOVJxYTBZeG03V2gw
        V016L01xVzRtaDJaazNUUW1sZVFMbGtkRmxVCmxxbUJaUm5wS080WTNseFZ6d1RN
        Nk9LcTVqNFR6bEtiaTBSb05rOE5sMVUKLS0tIFZ4dERWOEVrME9LS1VGMXBJaDl1
        NksvMUxuaE9keFpvTlRoWmdZS20vUFUKSz0ZXopehJSyd6pZ36+Sw3Tzo2WMYOmu
        jx0EWvQfkRd7dcF+j3RME21M0wCkLWtCJ0GALUwWSDFJMIgGxPxaRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T20:22:42Z"
  mac: ENC[AES256_GCM,data:P1Sb1JHkfMBOILdCbL+xT8z26vhRsYVR6VoPEIDTKclWyZblEOtbutvgwEPkGn5d1L/9fp9cZRc8zN2DZyd4Jmrl3BM3shX/mu0Wr36ticDPmtPE+5xKJa/NF+5Jrzi5MnvuvKiKnDbwkEO5KnusMB3jbXbPjwNAoJ5Od2qBakw=,iv:2AZVXUUDBwH8LqWWpFHRlvBUlVVQPR3ogQ2Tt/+Y1Qs=,tag:CZ5/OMjOcqcowVEnWggMDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
