---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: synology-csi-secrets
  namespace: synology-csi
spec:
  suspend: false
  secretTemplates:
    - name: synology-csi-client-credentials
      stringData:
        client-info.yml: ENC[AES256_GCM,data:PeQiqdisi7dvCx2fU8ToYF4Qi6lDPcj1Ew63MuYBOjD74FwB6k/OOar5u6efohp2+ZHFzXcQ59fKAdEv+O7fGCTRI0G9hrtc2DmEz3egxl5G/lIUGAX43JA5Xce7Vch8Di+N24tEoCbHbsJCI568Z7FRmChRbopq6lMJO7X5Abn26flHD877F0L90dstOz6sPQmqleF0W1B/y7l6v54ioJtyQjtflDKtPVtEBCUA5jdlL9UQVsaLz4/B95Eq1QubewzhaaS9RMCWx8E9wK8SDZ3H,iv:aewX72+CrxE3DPxAeErnx/RQByQjtJ33hfFJ4reTK2k=,tag:j0N78N4Ptt1c5u2W3hdYZg==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OGtaSXlrdnNPc3dCYXBZ
        YzM1YVJ3dkpRS3kveFlTb0NMbTl6ZHhaeUdzCmhJVlZxTFpSLzQzb1QzVlR1b09O
        cmprdHJackh4Zkl1ZkVIRnU5dnozL2cKLS0tIE0zMnBDTmpyRU5OaStTWXFhM1BR
        bGNPeXRNM0g1MWVqc0xmY1ZzR3VDQzQKFIo/vp9usfiS/RrzV3pDXbC0DU0C5PLw
        XRS7UX2wftcw/kO2qfHPX7xMl9rZPJZpyi8tYbV4AL7XWsa4z72KGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T21:11:16Z"
  mac: ENC[AES256_GCM,data:DFsF976EpmtHTOvAdGtkz+vam/aBRAmMUr1SP+EGvrG9nqRh/3ChhcLjrkL+jpFbnnM2ZpY4H2EzD9X8n7oD3wdU2ivQRWEJFiKSStn/XdRb1blJ8GoEGDBvMLQwEQZGBMpyEYZPdp5BsG3mUgioHL1LGAori8soJm7pYrCi054=,iv:jbwP0wI/4KGWJhsWpYzW8xExDrA5ZJIQ3IeIXn93kgE=,tag:6y/zsa6x9y8g7lqe9mgB4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
