---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: keycloak-secrets
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  suspend: false
  secretTemplates:
    - name: r2-creds
      stringData:
        ACCESS_KEY_ID: ENC[AES256_GCM,data:XWNaELY9YMD3NtSradUh2LqsMoZ2t8bhtzK6aWtVplQ=,iv:HmS1Rv5nRS2M630tFujZcG2nHoilA/5jfbhlLgVIojI=,tag:9Ofhdzc93r1cZT2/tuI5Jg==,type:str]
        ACCESS_SECRET_KEY: ENC[AES256_GCM,data:C+mo8vo18Y+TqvVjUceno6BH0yAX6UIea4bvnxOGMuuRifb619SnLf20ODILzsGkJD3i4zNIN1Z4+j9j3wn2DQ==,iv:rCbcQcD1UXdzAFFw3Bj2SjiJEUNGQRQoGB9PwTSOuMk=,tag:N0LQ1ENMG6Sb3E6QMgMOmw==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRUdQY0VndHd5aXJZbEZv
        MjFlTWtYU2lyZmFlOUk1Zy9yb0MxcGFGZUJZCjQxN2hRQ0R4WElMM1BPRmtTNGlo
        L3Y2Zk8xWVo4ckEraC9OTnYzalpzZmcKLS0tIGFCbGs5VmxXRW5LeHVpbEYwNUhw
        OXlxWnlLd1FoeVQ2R05WNHJkWFJiSW8KtNVFGQUXfu4+AUL1d7QdLmmgbdCfA+dx
        uaSVShHEV10ID/fywf7umRlOP1T8gl9MkmJVvxmxJ9P+yCOf7VCoLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-07T09:23:17Z"
  mac: ENC[AES256_GCM,data:MXbrphjROiYWdOcjVw165o+1KKBUiHd9rHK3EP9x+Pb6trw0Nn7mTS0sBJX3zC2n1eli9vHY0gTYABgzZkOusyxml67RTdMoxRs9DkB0DWYGhPERFL7y1ODM0+uOsm01eV9siLoQSwgangbmqQp76+jQMgqqG1qdsMQ2AWMLe+s=,iv:tihtZqXAWYz33KKrSFdMlUZRqIXJi+qLFJSEs9aOjnY=,tag:RwiBbGB5NiR8ISL4dVc2Sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
