---
externalDatabase:
  existingSecret: keycloak-db-app
  existingSecretHostKey: "host"
  existingSecretPortKey: "port"
  existingSecretUserKey: "username"
  existingSecretDatabaseKey: "dbname"
  existingSecretPasswordKey: "password"

postgresql:
  enabled: false
ingress:
  enabled: false
proxy: edge
proxyHeaders: xforwarded
production: true
replicaCount: 3
extraEnvVars:
  - name: KC_HOSTNAME
    value: https://auth.maddin.dev
  - name: KC_HOSTNAME_ADMIN
    value: https://keycloak.maddin.dev

resources:
  requests:
    memory: "1250Mi"
    cpu: "500m"
  limits:
    memory: "1500Mi"
    cpu: "1000m"
