---
externalDatabase:
  host: keycloak-db-rw
  port: 5432
  database: app
  existingSecret: keycloak-db-app
  existingSecretUserKey: "username"
  existingSecretPasswordKey: "password"

postgresql:
  enabled: false
ingress:
  enabled: false
proxyHeaders: xforwarded
production: true
replicaCount: 3
extraEnvVars:
  - name: KC_HOSTNAME
    value: https://auth.maddin.dev
  - name: KC_HOSTNAME_ADMIN
    value: https://keycloak.maddin.dev
  - name: KC_HTTP_ENABLED
    value: "true"

resources:
  requests:
    memory: "1250Mi"
    cpu: "500m"
  limits:
    memory: "1500Mi"
    cpu: "1000m"
