---
ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

service:
  annotations:
    lbipam.cilium.io/ips: "10.0.10.0"

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
