---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.18.1
      helm:
        valueFiles:
          - $app/apps/cert-manager/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/cert-manager
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
