---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  labels:
    app-type: infra
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.26.0
      helm:
        valueFiles:
          - $app/apps/cloudnative-pg/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/cloudnative-pg
    - repoURL: https://github.com/cloudnative-pg/plugin-barman-cloud
      targetRevision: v0.5.0
      path: .
      directory:
        recurse: false
        include: manifest.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ForceConflicts=true
