---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: keycloak
      targetRevision: 24.7.6
      helm:
        valueFiles:
          - $app/apps/keycloak/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/keycloak
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
