---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  labels:
    app-type: infra
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.17.7
      helm:
        valueFiles:
          - $app/apps/rook-ceph/values-operator.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/rook-ceph
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  labels:
    app-type: infra
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: v1.17.6
      helm:
        valueFiles:
          - $app/apps/rook-ceph/values-cluster.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/rook-ceph
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
