---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://isindir.github.io/sops-secrets-operator/
      chart: sops-secrets-operator
      targetRevision: 0.22.0
      helm:
        valueFiles:
          - $app/apps/sops-secrets-operator/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/sops-secrets-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: sops-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
