---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://zebernst.github.io/synology-csi-talos
      chart: synology-csi
      targetRevision: 0.9.4
      helm:
        valueFiles:
          - $app/apps/synology-csi/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_beelink_infra.git
      targetRevision: HEAD
      ref: app
      path: apps/synology-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: synology-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
